spring:
  project:
    name: spaserver
  datasource:
    url: jdbc:mysql://localhost:3306/spadb?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: examplepassword
#  sql.init.mode: always
  jpa:
    hibernate:
      ddl-auto: update
app:
  jwt:
    secret: ${JWT_SECRET:ultra_secure_jwt_secret}
  auth:
    cookieSecure: true